
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.Calendar; 




public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconSmall = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        EnrolmentLabel = new javax.swing.JLabel();
        IDNumLabel = new javax.swing.JLabel();
        SurnameTF = new java.awt.TextField();
        YearOfStudyTF = new java.awt.TextField();
        NameTF = new java.awt.TextField();
        EnrolmentCB = new javax.swing.JComboBox();
        EmploymentStatusLabel = new javax.swing.JLabel();
        YearOfStudyLabel = new javax.swing.JLabel();
        IDNumTF = new java.awt.TextField();
        jLabel9 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        InfoPanelBackground = new javax.swing.JPanel();
        GenderLabel = new javax.swing.JLabel();
        CitizenLabel = new javax.swing.JLabel();
        ValidLabel = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        DateOfBirthLabel = new javax.swing.JLabel();
        MajorTF = new java.awt.TextField();
        Employment = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enrolment by Jurie Spies @Airos Education");

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IconSmall.setIcon(new javax.swing.ImageIcon("C:\\Users\\jurie\\Documents\\airos icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 206, Short.MAX_VALUE)
                .addComponent(IconSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(IconSmall)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NameLabel.setBackground(new java.awt.Color(0, 0, 0));
        NameLabel.setText("Name :");

        SurnameLabel.setBackground(new java.awt.Color(0, 0, 0));
        SurnameLabel.setText("Surname :");

        EnrolmentLabel.setBackground(new java.awt.Color(0, 0, 0));
        EnrolmentLabel.setText("Enrolment :");

        IDNumLabel.setBackground(new java.awt.Color(0, 0, 0));
        IDNumLabel.setText("ID Number :");

        SurnameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SurnameTFKeyTyped(evt);
            }
        });

        YearOfStudyTF.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                YearOfStudyTFTextValueChanged(evt);
            }
        });
        YearOfStudyTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                YearOfStudyTFKeyTyped(evt);
            }
        });

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });
        NameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameTFKeyTyped(evt);
            }
        });

        EnrolmentCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arts student", "Entrepreneurship student", "Human resource student", "Tech student" }));

        EmploymentStatusLabel.setBackground(new java.awt.Color(0, 0, 0));
        EmploymentStatusLabel.setText("Employment status :");

        YearOfStudyLabel.setBackground(new java.awt.Color(0, 0, 0));
        YearOfStudyLabel.setText("Year of Study :");

        IDNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDNumTFActionPerformed(evt);
            }
        });
        IDNumTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDNumTFKeyTyped(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Major :");

        OkayButton.setText("Okay");
        OkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkayButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        InfoPanelBackground.setBackground(new java.awt.Color(255, 255, 255));

        GenderLabel.setBackground(new java.awt.Color(0, 0, 0));
        GenderLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(0, 0, 0));
        GenderLabel.setText("Gender :");

        CitizenLabel.setBackground(new java.awt.Color(0, 0, 0));
        CitizenLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        CitizenLabel.setForeground(new java.awt.Color(0, 0, 0));
        CitizenLabel.setText("SA Citizen :");

        ValidLabel.setBackground(new java.awt.Color(0, 0, 0));
        ValidLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        ValidLabel.setForeground(new java.awt.Color(0, 0, 0));
        ValidLabel.setText("Valid ID:");

        info.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        info.setForeground(new java.awt.Color(0, 0, 0));
        info.setText("Student Info :");

        AgeLabel.setBackground(new java.awt.Color(0, 0, 0));
        AgeLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(0, 0, 0));
        AgeLabel.setText("Age :");

        DateOfBirthLabel.setBackground(new java.awt.Color(0, 0, 0));
        DateOfBirthLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        DateOfBirthLabel.setForeground(new java.awt.Color(0, 0, 0));
        DateOfBirthLabel.setText("Date of Birth :");

        javax.swing.GroupLayout InfoPanelBackgroundLayout = new javax.swing.GroupLayout(InfoPanelBackground);
        InfoPanelBackground.setLayout(InfoPanelBackgroundLayout);
        InfoPanelBackgroundLayout.setHorizontalGroup(
            InfoPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(GenderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CitizenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        InfoPanelBackgroundLayout.setVerticalGroup(
            InfoPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelBackgroundLayout.createSequentialGroup()
                .addComponent(info)
                .addGap(15, 15, 15)
                .addComponent(AgeLabel)
                .addGap(18, 18, 18)
                .addComponent(DateOfBirthLabel)
                .addGap(18, 18, 18)
                .addComponent(GenderLabel)
                .addGap(18, 18, 18)
                .addComponent(CitizenLabel)
                .addGap(18, 18, 18)
                .addComponent(ValidLabel)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        MajorTF.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                MajorTFTextValueChanged(evt);
            }
        });
        MajorTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MajorTFKeyTyped(evt);
            }
        });

        Employment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Self-Employed", "Unemployed" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(SurnameLabel)
                                                .addComponent(NameLabel))
                                            .addGap(68, 68, 68))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(IDNumLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SurnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(NameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(IDNumTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YearOfStudyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(YearOfStudyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MajorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(EnrolmentLabel)
                                            .addGap(62, 62, 62)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(EnrolmentCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Employment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(EmploymentStatusLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(OkayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SurnameLabel)
                    .addComponent(SurnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(IDNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDNumLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(YearOfStudyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearOfStudyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MajorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmploymentStatusLabel)
                    .addComponent(Employment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnrolmentLabel)
                    .addComponent(EnrolmentCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkayButton)
                    .addComponent(ResetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(InfoPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void IDNumTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDNumTFKeyTyped
char c = evt.getKeyChar();
if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
    evt.consume();
}
if(IDNumTF.getText().length()>=13){
    evt.consume();
}

    }//GEN-LAST:event_IDNumTFKeyTyped

    private void YearOfStudyTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YearOfStudyTFKeyTyped
char c = evt.getKeyChar();
if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
    evt.consume();
}
    if(YearOfStudyTF.getText().length()>=4){
    evt.consume();
}


    
    }//GEN-LAST:event_YearOfStudyTFKeyTyped

    private void YearOfStudyTFTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_YearOfStudyTFTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_YearOfStudyTFTextValueChanged

    private void NameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTFKeyTyped
  char c = evt.getKeyChar();
if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
    evt.consume();
}

    }//GEN-LAST:event_NameTFKeyTyped

    private void SurnameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SurnameTFKeyTyped
char c = evt.getKeyChar();
if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
    evt.consume();
}

    }//GEN-LAST:event_SurnameTFKeyTyped

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
NameTF.setText("");
SurnameTF.setText("");
IDNumTF.setText("");
YearOfStudyTF.setText("");
MajorTF.setText("");

    }//GEN-LAST:event_ResetButtonActionPerformed

    private void OkayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkayButtonActionPerformed
        
        /*****************Get Age from ID*****************/
        
        int year = Calendar.getInstance().get(Calendar.YEAR);
        int before2000 = 1900;
        int after2000 = 2000;
        
        String IDNUMBER = IDNumTF.getText();
        String FirstTwoNumbersOfIDNum = IDNUMBER.substring(0, 2);
        int StudentIDYear = Integer.parseInt(FirstTwoNumbersOfIDNum);
        int Age = year - StudentIDYear;
        
        if (StudentIDYear <= 99) {
            Age = year - (StudentIDYear + before2000);
            System.out.println(Age);
        }

        if (StudentIDYear <= 19) {
            Age = year - (StudentIDYear + after2000);
            System.out.println(Age);
        }

        if (StudentIDYear <= 9) {
            Age = year - (StudentIDYear + after2000);
        }

        
        /*****************Get Date Of Birth from ID*****************/
        String FirstSixNumbersOfIDNum = IDNUMBER.substring(0,6);
        StringBuilder strSix = new StringBuilder(FirstSixNumbersOfIDNum);

        strSix.insert(2, '-' );
        strSix.insert(5, '-' );
        
        
            if (strSix.charAt(0) == '0' || strSix.charAt(0) == '1') {
            strSix.insert(0, "20" );
            }
        
        
            else
            strSix.insert(0, "19" );
            
        
            
        /*****************Get Gender*****************/
            
            
            
            String NumbersOfIDNum = IDNUMBER.substring(6,10);
            int intNumbersOfIDNum=Integer.parseInt(NumbersOfIDNum);
            String Gender = "";
            
            if (intNumbersOfIDNum > 0000 && intNumbersOfIDNum < 4999 ){
                Gender = "Female";
            }
            
            if (intNumbersOfIDNum > 4999 && intNumbersOfIDNum < 9999 ){
                Gender = "Male";
            }
                
            
        /*****************SA Citizen *****************/     
            String Number11OfIDNum = IDNUMBER.substring(10,11);
            int intNumber11OfIDNum = Integer.parseInt(Number11OfIDNum);
            String Citizen = "";
            
            if (intNumber11OfIDNum == 0 ){
                Citizen = "SA Citizen";
            }
            
            if (intNumber11OfIDNum == 1 ){
                Citizen = "Permanent Resident";
            }
            
            if (intNumber11OfIDNum > 1 ){
                Citizen = "Not South African";
            }

        /*****************Valid ID *****************/ 
  
        String IDValid = IDNUMBER.replaceAll("(.{1})", "$1,");       //  9,0,0,3,2,0,5,1,1,8,0,8,1,
//        String [] SplitID = IDValid.split(",");                      
//        String  ArraySplitIDToString = Arrays.toString(SplitID);    //  [9,0,0,3,2,0,5,1,1,8,0,8,1]
//        Integer result = Integer.valueOf(IDNUMBER);
//        int[] array = Arrays.asList(IDValid).stream().mapToInt(Integer::parseInt).toArray();
        
        for(int i = 0; i < IDNUMBER.length() ;
        i++)
            
            if (i % 2 == 1) {
                IDNUMBER.substring(i, i + 1);
            }
            
        
            
            
            
            
            
            
        //9003205118081  



        info.setText("Student Info : " + NameTF.getText() + " " +SurnameTF.getText() +" " + EnrolmentCB.getSelectedItem());
        AgeLabel.setText("Age : " + Age);
        DateOfBirthLabel.setText("Date of Birth : " + strSix) ;
        GenderLabel.setText("Gender : " + Gender );
        CitizenLabel.setText("SA Citizen : " + Citizen );
        ValidLabel.setText("Valid ID: " + IDNUMBER );
        
    }//GEN-LAST:event_OkayButtonActionPerformed

    private void IDNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDNumTFActionPerformed

    private void MajorTFTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_MajorTFTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_MajorTFTextValueChanged

    private void MajorTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MajorTFKeyTyped
 char c = evt.getKeyChar();
if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
    evt.consume();
}
    }//GEN-LAST:event_MajorTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel CitizenLabel;
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JComboBox Employment;
    private javax.swing.JLabel EmploymentStatusLabel;
    private javax.swing.JComboBox EnrolmentCB;
    private javax.swing.JLabel EnrolmentLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel IDNumLabel;
    public java.awt.TextField IDNumTF;
    private javax.swing.JLabel IconSmall;
    private javax.swing.JPanel InfoPanelBackground;
    private java.awt.TextField MajorTF;
    private javax.swing.JLabel NameLabel;
    private java.awt.TextField NameTF;
    public static final transient javax.swing.JButton OkayButton = new javax.swing.JButton();
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel SurnameLabel;
    public java.awt.TextField SurnameTF;
    private javax.swing.JLabel ValidLabel;
    private javax.swing.JLabel YearOfStudyLabel;
    public java.awt.TextField YearOfStudyTF;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
